FROM php:8.3-apache

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Copiar archivos al contenedor
COPY . /var/www/html/

# Exponer el puerto 80
EXPOSE 80

